### PR TITLE
Allow ACL ID to be writeable

### PR DESCRIPTION
**Pull request by robrankin**
Proposed fix from @rytutis for issue #192.  Feel free to rubbish, neither of us are Ruby folks :)

### CODE REVIEW

**Comment by aj-jester** [comment]
Do we have any use for `get_resource_id` method anymore?

**Comment by split3** [comment]
Is there anything else specifically that we need to merge this in?

**Comment by solarkennedy** [comment]
Mostly to address @aj-jester's question about `get_resource_id`. If we don't need it, junk it.

**Comment by aj-jester** [comment]
oh yah, the PR looks good. I was just wanted to know if there was a need for it.

:bullettrain_side: LGTM

**Pull request merged**
