### PR TITLE
Allow for alias_service checks

### PR DESCRIPTION
**Pull request by genebean**
This PR also adjusts the whitespace in lib/puppet/functions/consul/validate_checks.rb to make it more readable.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you rebase/merge on master? (the tests were broken before)

**Comment by genebean** [comment]
Just merged in master @solarkennedy

**Comment by genebean** [comment]
any chance of getting this pr merged?

**Comment by bastelfreak** [comment]
Hi @genebean ! thanks for the PR.

**Comment by genebean** [comment]
Thanks @bastelfreak

**Comment by genebean** [comment]
@bastelfreak any idea when a new release might go out that includes this?

**Comment by solarkennedy** [comment]
It has been a while. I'll make a release today.
I think in theory any contributor can make a release if tagged correctly.

**Comment by genebean** [comment]
Much appreciated!

**Comment by genebean** [comment]
@solarkennedy if it suits you, I’ll submit some additional updates post release that include dropping end of life OSs, replacing legacy facts, and other general updates.

**Comment by solarkennedy** [comment]
@genebean  yes please! `6.2.0` is released now. Let's queue up anything up you want, if you think it will be significant enough we could do a major release.

**Comment by genebean** [comment]
Sounds good. I can already say I’d recommend a major version bump as several EoL operating systems will be dropped as will puppet less than 6.1.0. I started it a little while ago and will push a draft PR soon so conversation can continue there.

**Pull request merged**
