### PR TITLE
PDK update, move CI to GH Actions

### PR DESCRIPTION
**Pull request by genebean**
This includes many changes that are a byproduct of updating to the latest version of the PDK. All unit tests pass at this stage but several RuboCop tests still fail.

Tht GH Action was copied from a Vox Pupuli module. Their module testing is pretty slick and utilizes Beaker just as this one has traditionally done so it seems like a good place to start. A couple of lines were commented out as the Gemfile from the PDK doesn't line up exactly with the one used by most Vox Pupuli modules.

RuboCop is disabled for the moment as it is known that those tests do not yet pass.

An example of this branch and the new CI process can be seen in https://github.com/genebean/puppet-consul/pull/1

This PR is built atop #573 and includes its change.

### CODE REVIEW

**Comment by genebean** [comment]
@solarkennedy - if you are game, it would be good to enable https://github.com/apps/puppet-community-rangefinder on your modules, or just enable it for your account as it won't hurt anything (that's what I did). I am doing some debugging of CI bits on my fork and you can see its output there: https://github.com/genebean/puppet-consul/pull/1

**Review by bastelfreak — APPROVED** [review]

**Comment by bastelfreak** [comment]
@solarkennedy can you take a look here as well because that's a bigger PR.

**Comment by solarkennedy** [comment]
Hard to review super well, but it still looks fine to me.
In the readme I noticed the new facts lookup, which is new to me.
I'm glad to see the nodeset stuff go away.

Apparently github actions don't work yet, I guess because of the branch.
I'll merge, and let's see if we can get them green on master.

**Comment by genebean** [comment]
It should be green now. I had the branch running in my fork - results are linked in the top comment. I’m going to start working on the rubocop bits next

**Pull request merged**
