### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by spuder**

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you fix :239 while you are at it?

**Comment by spuder** [comment]
Could you give me a link? #239 doesn't seem related.

**Comment by solarkennedy** [comment]
https://github.com/solarkennedy/puppet-consul/pull/489/files/e9b2fd1daed742fdb11acaca524fdf5812fbfb25..a2080d55aa414e8056b9b1fb3ba736e23f1f5541#diff-04c6e90faac2675aa89e2176d2eec7d8R243

Line 243 now, `Crate`

**Comment by spuder** [comment]
Fixed

**Comment by solarkennedy** [comment]
👍 Thank you.

**Pull request merged**
