### PR TITLE
Pretty json config

### PR DESCRIPTION
**Pull request by teaforthecat**
render pretty json into /etc/consul/config.json

### CODE REVIEW

**Comment by aj-jester** [comment]
Hmmm, whats the reason for this?

**Comment by teaforthecat** [comment]
I thought it would be nice to read /etc/consul/config.json with newlines in it. It's more readable.

**Comment by teaforthecat** [comment]
I'll add some newlines to the other tests that I missed

**Comment by aj-jester** [comment]
I'm assuming the only time someone would need to read the config is while troubleshooting.

Why not do something simple one-liner like:
```
ruby -e "require 'json'; puts (JSON.pretty_generate JSON.parse(IO.read('/etc/consul/config.json')))"
```

This way we keep the codebase lean. @solarkennedy thoughts?

**Comment by teaforthecat** [comment]
We're dealing with system administrators here. Asking them to run that command above to look at a file would produce some funny looks. I understand the ideal situation is where no one logs onto the server at all. In reality, though it happens a lot, and it would be nice to have a readable configuration file when someone does want to take a look. Also, imho, this version is a little easier to read.

**Comment by solarkennedy** [comment]
`cat file.json | jq .`

I was sad when I had to write this function in the first place, I don't really want to see it grow.

Can't we just stick our own JSON.pertty_generate() on our object in the function at the last second when we return?

**Comment by aj-jester** [comment]
One of my biggest concerns with this is whitespace related changes. I don't think anyone wants a restart because of it :worried:.

If we do decide to implement this, can we at least make it conditional with "pretty" being turned off by default?

**Comment by split3** [comment]
I agree, this should at least be conditional.

**Comment by solarkennedy** [comment]
With two votes for it being a conditional option, I'm going to veto adding this to the module. For pretty printing any json file I recommend `jq . your.json`

**Comment by solarkennedy** [comment]
Sorry :(

**Pull request closed without merging**
