### PR TITLE
force integer on SRV weights

### LINKED ISSUE #492: service weights needs integer
starting from Consul 1.6.x, the service weight requires an integer, but since this is configured with the extra hash `service_config_hash`, I am not being to set the integer in the json file. 

This is what I had in my puppet manifest (I have also tried the trick of using `0 +`, to force integer, but it didn't work:

```
  consul::service { 'puppet':
    service_name        => 'puppet',
    enable_tag_override => false,
    checks              => [
      {
        args     => ['/usr/local/bin/puppet-check.sh'],
        interval => '10s'
      }
    ],
    port                => 8140,
    tags                => [
      '_x-puppet._tcp',
      '_x-puppet-fileserver._tcp'
    ],
    service_config_hash =>  {
      weights => {
        passing => 10,
        warning => 1
      }
    }
  }
```

### PR DESCRIPTION
**Pull request by maxadamo**
resolves #492

### CODE REVIEW

**Comment by bastelfreak** [comment]
@maxadamo thanks for the patch. can you take a look at the failing travis tests?

**Comment by maxadamo** [comment]
@bastelfreak yep.... connecting Travis to my fork on my account.

**Comment by solarkennedy** [comment]
You shouldn't have to do anything fancy. Here is a direct link to a failure:
https://travis-ci.org/solarkennedy/puppet-consul/jobs/588161817#L558

**Comment by maxadamo** [comment]
@solarkennedy I know and I have seen it, but I don't want to keep committing on your repo until it succeeds. 
I rather like doing it on my repo.

**Comment by solarkennedy** [comment]
Haha, it is totally fine. It is all self contained on a pull request. You can make as many commits as you want till you get it right! You can also try to run the tests locally if you want for a faster development cycle.

**Comment by maxadamo** [comment]
@solarkennedy @bastelfreak  ... back to this issue ... the problem is that what I see from the Travis output, does not reflect what I get on my puppet server. 
I have tried to roll the change back on my puppet server now, and I get the quotes surrounding the integer. I put my change back in place and the integer is without quotes. It works like a charm. 
p.s.: I am not an expert with Travis

**Comment by solarkennedy** [comment]
```
     Failure/Error:
       should contain_file("/etc/consul/service_my_service.json") \
         .with_content(/"passing":(\s|)10/)
     
       expected that the catalogue would contain File[/etc/consul/service_my_service.json] with content set to /"passing":(\s|)10/ but it is set to "{\"service\":{\"checks\":[],\"enable_tag_override\":false,\"id\":\"my_service\",\"name\":\"my_service\",\"tags\":[],\"weights\":{\"passing\":\"10\",\"warning\":\"1\"}}}"
     # ./spec/defines/consul_service_spec.rb:178:in `block (5 levels) in <top (required)>'
```

Does the code recursively disable quotes on all things under `weights`?

**Comment by maxadamo** [comment]
@solarkennedy on my puppet server, yes, it does :man_shrugging:

**Comment by solarkennedy** [comment]
@maxadamo can you rebase on master to get the latest travis matrix?

**Comment by maxadamo** [comment]
will try that, probably today.

**Comment by maxadamo** [comment]
yesss! Finally fixed ... sorted_json.rb has two lambda 
One does `sorted_generate`, the other one does  `sorted_pretty_generate`. 
I was using pretty_config and the spec_test was not using pretty_config. I have now set the same parameter on both lambdas and it started working.

**Comment by maxadamo** [comment]
please check PR  #509

**Pull request closed without merging**
