### PR TITLE
Added support for checks with service_id, http, and timeouts

### PR DESCRIPTION
**Pull request by split3**
Added the various options for checks.  Left all validation logic in place and added more tests to validate new features.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Nice! I'll wait to hear from travis, but this looks great.

**Comment by centromere** [comment]
Thank you for this.

**Comment by split3** [comment]
Do you want to merge this pull request now or wait until the services portion is updated as well?

**Comment by split3** [comment]
I've got the service support added now with some other additions, I'm going to just close this pull request and open a new one.

**Pull request closed without merging**
