### PR TITLE
ACL fixes - idempotentcy and port bug.

### PR DESCRIPTION
**Pull request by sigerber**
Implemented prefetch so that multiple puppet runs will not attempt to recreate the ACLs. Also fixed ACLs not working due to a typo introduced by the addition of the port parameter.

Note: I've only been playing with puppet for a couple of weeks so this isn't necessarily the best implementation. I'm also a bit uncomfortable about the reliance on 'port' and 'acl_api_token' needing to be correct across all tokens or bad things might happen.

### CODE REVIEW

**Comment by solarkennedy** [comment]
@sigerber does this actually make `puppet resource consul_acl` spit stuff out?

@michaeltchapman or @mdelagrange can you code review this?

**Comment by sigerber** [comment]
Sorry, no. You need to implement 'self.instances' for that - but self.instances doesn't take any parameters, so there isn't a way AFAIK to feed in the port and ACL token. This just fixes the port and id bug and stops puppet trying to create the resource every time there is a puppet run.

**Comment by mdelagrange** [comment]
seems reasonable to me

**Comment by solarkennedy** [comment]
@sigerber can you merge master then I'll merge it in?

**Comment by sigerber** [comment]
@solarkennedy Done - and hopefully did it right.

**Comment by solarkennedy** [comment]
Thanks! I (personally) am not a user of this particular feature of this module, and we don't have a lot of test coverage on these, so we're going to depend on you and the other users on this thread to test this irl.

**Pull request merged**
