### PR TITLE
Updated download_urls used to be the new releases.hashicorp.com location

### PR DESCRIPTION
**Pull request by split3**

### CODE REVIEW

**Comment by split3** [comment]
@aj-jester and @solarkennedy If we can get this merged in I'm also going to attempt to commit some changes that allow for the upgrading via URL to follow the similar approach that consul-template uses which seems to work decently well.

**Comment by aj-jester** [comment]
:bullettrain_side: LGTM

**Comment by solarkennedy** [comment]
@split3 of course don't forget you are a collaborator, so feel free to merge if something is blocking you. These kind of changes are pretty much always a shipit.

**Comment by split3** [comment]
@solarkennedy yea I know, but its been a while so wanted to make sure to get another :+1: from other collaborators.

**Pull request merged**
