### PR TITLE
Add Ubuntu 18.04 / 16.04 support

### PR DESCRIPTION
**Pull request by bastelfreak**
This should be merged after https://github.com/solarkennedy/puppet-consul/pull/416

### CODE REVIEW

**Comment by solarkennedy** [comment]
Nice. Can you rebase on master?

**Comment by bastelfreak** [comment]
so in general this works, I only need to convince beaker to install puppet5 on ubuntu18.04 and not puppet 4. There is probably an option for that.

**Comment by bastelfreak** [comment]
@solarkennedy can you please review and merge?

**Comment by solarkennedy** [comment]
Thanks!

**Pull request merged**
