### PR TITLE
Added support for consul 0.5.0 features:

### PR DESCRIPTION
**Pull request by split3**
Added support for checks with service_id, http, and timeouts
Added address to consul::service
Switch checks to array in consul::service
Added consul_validate_checks.rb to handle the validation logic for checks in both consul::service and consul::check

### CODE REVIEW

**Comment by solarkennedy** [comment]
Super great!!!

**Comment by solarkennedy** [comment]
Thanks!

**Comment by solarkennedy** [comment]
@split3 you are now an official contributor!
Feel free to work directly on this remote, no need to fork. But please continue to do PR's with any non-trivial changes.

**Comment by split3** [comment]
Awesome will do, thank you very much!

**Pull request merged**
