### PR TITLE
Bump upper version range for puppetlabs/stdlib

### PR DESCRIPTION
**Pull request by jay7x**
Current stdlib version is 6.1.0 so it's good idea to bump upper version range to 7.0.0

### CODE REVIEW

**Comment by jay7x** [comment]
This closes #496

**Comment by jay7x** [comment]
It'd be great to release v0.5.2 with this change if possible

**Comment by bastelfreak** [comment]
@jay7x can you please also bump the dependency for the archive module? It currently conflicts with stdlib 6.x.

**Comment by jay7x** [comment]
I'll close this one and do proper PR instead

**Pull request closed without merging**
