### PR TITLE
Add protocol option for ACL operations (http/https), defaults to http, like before

### LINKED ISSUE #217: Support talking to Consul over https for ACL operations

### PR DESCRIPTION
**Pull request by gozer**
Fixes #217

### CODE REVIEW

**Comment by split3** [comment]
Could you add a test around this?

**Comment by solarkennedy** [comment]
Also looks sane to me. @split3 ?

**Comment by split3** [comment]
Looks good, depending on which one we merge first, we'll probably need to do some conflict resolution though @gozer  said he would take care of it.

**Comment by solarkennedy** [comment]
Yep. @gozer can you rebase/merge and I'll click the button?

**Comment by split3** [comment]
@gozer just waiting on a rebase for this, if you can get that done we can merge it up.

**Comment by blsmth** [comment]
ping! would be nice to have this

**Comment by split3** [comment]
There are merge conflicts on this pull request that need to be fixed.  That is all we are waiting for.

**Pull request closed without merging**
