### PR TITLE
(#359) Datacenter support to consul_key_value

### LINKED ISSUE #363: Consul k/v does not update to new value
It looks like the k/v resource will not update to a new value if you set that.
Changing to absent first and then re-apply-ing does.

### PR DESCRIPTION
**Pull request by houtmanj**
This includes tests for the provider that mock the consul API

Fixes #363

### CODE REVIEW

**Comment by houtmanj** [comment]
same problem with travis, i asked their support for help

**Comment by solarkennedy** [comment]
This looks pretty good. Can you expand the section on the k/v in the README and then I'll merge and make a major release.

**Comment by houtmanj** [comment]
Sure,

If you can want to wait  a little longer.
I was planning on optimizing the code so that we only update consul when we
need changes.

And if you want it in the module:
I am starting to build a function to query the kv.
Something along the lines of:
$data = consul::key_value_query(path)

Jos

**Comment by leeuwenrjj** [comment]
Any change we can see this merged?

**Comment by solarkennedy** [comment]
omg once again I neglected to click the "submit review" button which has delayed this. @houtmanj please fix the few minor issues and I will merge. It is ok to add future functions in a new PR.

**Comment by houtmanj** [comment]
This what you intended?

**Comment by solarkennedy** [comment]
Looks great!

**Pull request merged**
