### PR TITLE
Keep the quotes for integers in "tags" and "node_meta" keys

### LINKED ISSUE #283: Quoted integer (string) to integer is breaking tags
In https://github.com/solarkennedy/puppet-consul/issues/119 quoted things that look like integers are explicitly turned into integers.

This breaks if you want a tag such as `"tags": ["106"]` as now you turn this into `"tags": [106]` and `consul` will no longer start, giving the error:
`* 'Tags[0]' expected type 'string', got unconvertible type 'float64'`.

Would it be possible just target areas of the config where you know the value needs to be an int instead of blanket changing them?

Thanks.

### PR DESCRIPTION
**Pull request by mmickan**
Without this change, integer values under tags and node_meta keys are not
quoted.  This results in errors from Consul such as:

* 'Tags[0]' expected type 'string', got unconvertible type 'float64'
* 'node_meta[cpu_count]' expected type 'string', got unconvertible type 'float64'

Fixes #283

### CODE REVIEW

**Comment by solarkennedy** [comment]
Can you add a test to ensure this continues to work over time?

**Comment by jardleex** [comment]
Hey there, is there a good chance to get this one fixed? We're moving more and more into Consul based on this module and I'm getting more use cases where these metadata would be handy.

**Comment by bastelfreak** [comment]
@jardleex this PR is lacking tests and needs another rebase. Are you interested in picking this work up and continue it?

**Comment by jardleex** [comment]
As much as I like to, the lack of any knowledge in Ruby and the tests to provide prevent me from doing so.

**Pull request closed without merging**
