### PR TITLE
Hiera Backend and code re-use

### PR DESCRIPTION
**Pull request by houtmanj**
Its to early to merge this

But I already introduces a fair bit of code re-use, tests, bugfixes and lint fixes.

### CODE REVIEW

**Comment by houtmanj** [comment]
@solarkennedy Any idea as to why this fails on puppet 4.1?

more specifically it fails if i run the tests through rake spec with puppet 4.1
But if I execute the tests seperatly  through rspec  <specfile>  then all tests succeed.

**Comment by solarkennedy** [comment]
@houtmanj is this ready for review?

**Comment by houtmanj** [comment]
@solarkennedy yes

**Comment by bastelfreak** [comment]
Hey @houtmanj, could you please rebase?

**Pull request closed without merging**
