### PR TITLE
Add hostname proprety for ACL operations, defaults to localhost, like before

### LINKED ISSUE #216: Support creating ACLs while talking to a hostname other than localhost
Right now, port is configurable, but the hostname is always localhost

### PR DESCRIPTION
**Pull request by gozer**
Fixes #216

### CODE REVIEW

**Comment by split3** [comment]
If you could add tests that would be great for this one as well.  Also it would probably be fine to combine these two together into a single pull request if you'd like.  Otherwise we might end up with having to do some merge conflict resolution since this and your other are changing several of the same lines of code.

**Comment by gozer** [comment]
Tests will be on their way soon. As for the merge conflicts, I'll handle them, I'd rather keep logically different changes in different PRs

**Comment by solarkennedy** [comment]
Looks good to me. @split3 second opinion?

**Comment by split3** [comment]
Yes agree, looks good, thanks for adding the test!

**Comment by solarkennedy** [comment]
Thanks!

**Pull request merged**
