### PR TITLE
Some linting fixes and resolves joining wan not actually joining the wan

### PR DESCRIPTION
**Pull request by justicel**

### CODE REVIEW

**Comment by solarkennedy** [comment]
Whoa!

**Comment by solarkennedy** [comment]
Can you paste the actual output of `consul members -wan -detailed` ?

It's certainly possible we've been wrong this whole time, but I would like to see your output to confirm.

**Comment by justicel** [comment]
Here are two entries from two different clusters:

web1east.east         10.30.0.13:8302   alive   role=consul,dc=east,vsn=2,vsn_min=1,vsn_max=2,build=0.4.1:,port=8300,expect=3
background3.west      10.20.0.48:8302   alive   build=0.4.1:,port=8300,expect=3,role=consul,dc=west,vsn=2,vsn_min=1,vsn_max=2

Essentially if the data-center that the server is in isn't attached to the remote data-center there will be no entries returned by the -vP grep which will then generate an exit 1 code which runs the exec command, thus is must be an 'unless' statement. Trust me, I tested the exit results thoroughly.

**Comment by solarkennedy** [comment]
Ok. Can you rebase without the init style changes and only have the wan-join thing?

**Comment by justicel** [comment]
I can remove those but I suggest leaving them. They are lint fixes as you are not supposed to use selectors inside of resource definitions. I can link to the puppet documentation on this point if you'd like.

**Comment by solarkennedy** [comment]
Ah nevermind. Ship!

**Comment by justicel** [comment]
Will you be merging this or is there changes still outstanding you'd like me to make?

**Comment by solarkennedy** [comment]
Yes, please rebase on master so I can click the merge button.

**Comment by solarkennedy** [comment]
@EvanKrall do you have a second opinion? How was wan joining working for us this time?

**Comment by EvanKrall** [comment]
I haven't bumped our puppet-consul module in a long time, and our profile_consul handles wan joining.

This lg2m.

**Comment by justicel** [comment]
Okay, should be good to go now.

**Comment by solarkennedy** [comment]
Whew! Thanks.

**Pull request merged**
